package tool.common

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

class Config  {
	public static Map<String,String> namingMap =new HashMap<String,String>()
	static{
		Config.namingMap.put("ＬＲＭＳ介護_T_LRMS_CARE_HOSHO_KIHON", "lrmsKaigoTLrmsCareHoshoKihon")
		Config.namingMap.put("ＬＲＭＳ相続_T_LRMS_SOGAKU_KIHON", "lrmsSouzokuTLrmsSogakuKihon")
		Config.namingMap.put("ＬＲＭＳ相続_T_LRMS_SOGAKU_ZISN", "lrmsSouzokuTLrmsSogakuZisn")
		Config.namingMap.put("ＬＲＭＳ介護_Lcsc0501Collection", "lrmsKaigoLcsc050Collection")
		Config.namingMap.put("ＬＲＭＳ相続_Lisc0001Collection", "lrmsSouzokuLisc0001Collection")
		Config.namingMap.put("ＬＲＭＳ相続_Lisc000101Collection", "lrmsSouzokuLisc000101Collection")
		Config.namingMap.put("ＬＲＭＳ相続_lbsc0002Collection", "lrmsSouzokulbsc0002Collection")
		
		Config.namingMap.put("ＬＲＭＳセカンドライフ_T_LRMS_2LF_HYSKN_EVENT", "transferTLrms2LfHysknEvent")
		Config.namingMap.put("ＬＲＭＳセカンドライフ_T_LRMS_2LF_HYSKN_JUTAKU", "transferTLrms2LfHysknJutaku")
		Config.namingMap.put("ＬＲＭＳセカンドライフ_T_LRMS_2LF_HYSKN_LIFE", "transferTLrms2LfHysknLife")
		Config.namingMap.put("ＬＲＭＳセカンドライフ_T_LRMS_2LF_HYSKN_OTHER", "transferTLrms2LfHysknOther")
		Config.namingMap.put("ＬＲＭＳセカンドライフ_T_LRMS_2LF_JZSKN_NKJKM", "transferTLrms2LfJzsknNkjkm")
		Config.namingMap.put("ＬＲＭＳセカンドライフ_T_LRMS_2LF_JZSKN_NKKNM", "transferTLrms2LfJzsknNkknm")
		Config.namingMap.put("ＬＲＭＳセカンドライフ_T_LRMS_2LF_JZSKN_OTHER", "transferTLrms2LfJzsknOther")
		Config.namingMap.put("ＬＲＭＳセカンドライフ_T_LRMS_2LF_JZSKN_SHUNYU", "transferTLrms2LfJzsknShunyu")
		Config.namingMap.put("ＬＲＭＳセカンドライフ_T_LRMS_2LF_KIHON", "transferTLrms2LfKihon")
		
		
		
		Config.namingMap.put("ＬＲＭＳ死亡保障_L_T_LRMS_2LF_KIHON", "transferTLrms2LfKohon")
		Config.namingMap.put("ＬＲＭＳ死亡保障_L_T_LRMS_DIH_HYSKN_EDUC", "transferTLrmsDihHysknEduc")
		Config.namingMap.put("ＬＲＭＳ死亡保障_L_T_LRMS_DIH_HYSKN_JUTAKU", "transferTLrmsDihHysknJutaku")
		Config.namingMap.put("ＬＲＭＳ死亡保障_L_T_LRMS_DIH_HYSKN_KEKKON", "transferTLrmsDihHysknKekkon")
		Config.namingMap.put("ＬＲＭＳ死亡保障_L_T_LRMS_DIH_HYSKN_OTHER", "transferTLrmsDihHysknOther")
		Config.namingMap.put("ＬＲＭＳ死亡保障_L_T_LRMS_DIH_HYSKN_LIFE", "transferTLrmsDihHysknLife")
		Config.namingMap.put("ＬＲＭＳ死亡保障_L_T_LRMS_DIH_HYSKN_SHIBO", "transferTLrmsDihHysknShibo")
		Config.namingMap.put("ＬＲＭＳ死亡保障_L_T_LRMS_DIH_JZSKN_NKJKM", "transferTLrmsDihJzsknNkjkm")
		Config.namingMap.put("ＬＲＭＳ死亡保障_L_T_LRMS_DIH_JZSKN_NKKNM", "transferTLrmsDihJzsknNkknm")
		Config.namingMap.put("ＬＲＭＳ死亡保障_L_T_LRMS_DIH_JZSKN_OTHER", "transferTLrmsDihJzsknOther")
		Config.namingMap.put("ＬＲＭＳ死亡保障_L_T_LRMS_DIH_JZSKN_SHUNYU", "transferTLrmsDihJzsknShunyu")
		
		
		Config.namingMap.put("ＬＲＭＳ死亡保障_Llsc0201Collection", "transferLlsc0201Collection")
		Config.namingMap.put("ＬＲＭＳ死亡保障_Llsc020201Collection", "transferLlsc020201Collection")
		Config.namingMap.put("ＬＲＭＳ死亡保障_Llsc020202Collection", "transferLlsc020202Collection")
		Config.namingMap.put("ＬＲＭＳ死亡保障_Llsc020203Collection", "transferLlsc020203Collection")
		Config.namingMap.put("ＬＲＭＳ死亡保障_Llsc020204Collection", "transferLlsc020204Collection")
		Config.namingMap.put("ＬＲＭＳ死亡保障_Llsc020205Collection", "transferLlsc020205Collection")
		Config.namingMap.put("ＬＲＭＳ死亡保障_Llsc020206Collection", "transferLlsc020206Collection")
		Config.namingMap.put("ＬＲＭＳ死亡保障_Llsc0204Collection", "transferLlsc0204Collection")
		Config.namingMap.put("ＬＲＭＳ死亡保障_Llsc020501Collection", "transferLlsc020501Collection")
		Config.namingMap.put("ＬＲＭＳ死亡保障_Llsc020502Collection", "transferLlsc020502Collection")
		Config.namingMap.put("ＬＲＭＳ死亡保障_Llsc020503Collection", "transferLlsc020503Collection")
		Config.namingMap.put("ＬＲＭＳ死亡保障_Llsc0207Collection", "transferLlsc0207Collection")
		
		
		Config.namingMap.put("_Lrsc0301Collection", "transferLrsc0301Collection")
		Config.namingMap.put("_Lrsc030201Collection", "transferLrsc030201Collection")
		Config.namingMap.put("_Lrsc030202Collection", "transferLrsc030202Collection")
		Config.namingMap.put("_Lrsc030203Collection", "transferLrsc030203Collection")
		Config.namingMap.put("_Lrsc030204Collection", "transferLrsc030204Collection")
		Config.namingMap.put("_Lrsc0304Collection", "transferLrsc0304Collection")
		Config.namingMap.put("_Lrsc030501Collection", "transferLrsc030501Collection")
		Config.namingMap.put("_Lrsc030502Collection", "transferLrsc030502Collection")
		Config.namingMap.put("_Lrsc030503Collection", "transferLrsc030503Collection")
		Config.namingMap.put("_Lrsc030701Collection", "transferLrsc030701Collection")
		
		Config.namingMap.put("ＬＲＭＳ医療保障_Lmsc0401Collection", "transferLmsc0401Collection")
		Config.namingMap.put("ＬＲＭＳ医療保障_Lmsc0402Collection", "transferLmsc0402Collection")
		Config.namingMap.put("ＬＲＭＳ医療保障_Lmsc0403Collection", "transferLmsc0403Collection")
		Config.namingMap.put("ＬＲＭＳ医療保障_Lmsc0405Collection", "transferLmsc0405Collection")
		
		
		Config.namingMap.put("ＬＲＭＳ医療保障_L_T_LRMS_2LF_KIHON", "transferTLrms2LfKihon")
		Config.namingMap.put("ＬＲＭＳ医療保障_L_T_LRMS_IRH_LFSKBY", "transferTLrmsIrhLfskby")
		Config.namingMap.put("ＬＲＭＳ医療保障_L_T_LRMS_IRH_SHIPPEI_SELECT", "transferTLrmsIrhShippeiSelect")
		
		Config.namingMap.put("共通部_T_KRNS_PLAN_FAMILY", "transferKyoutsuTKrnsPlanFamily")
		Config.namingMap.put("共通部_LtPlanCollection", "transferKyotsuLtPlanCollection")
		Config.namingMap.put("共通部_PlanFamilyCollection", "transferKyotsuPlanFamilyCollection")
		Config.namingMap.put("共通部_Lasc1100Collection" ,"transferKyotsuLasc1100Collection")
		Config.namingMap.put("共通部_Lasc1201Collection" ,"transferKyotsuLasc1201Collection")
		Config.namingMap.put("共通部_LnasGlobalModelCollection" ,"transferKyotsuLnasGlobalModelCollection")
		Config.namingMap.put("共通部_LnasPrintModelCollection" ,"transferKyotsuLnasPrintModelCollection")
		Config.namingMap.put("共通部_LtPensionCollection" ,"transferKyotsuLtPensionCollection")
		Config.namingMap.put("共通部_LnasPrintModelSasaeruCollection"  , "transferKyotsuLnasPrintModelSasaeruCollection")
		

		
		Config.namingMap.put("ライフイベント_Lasc3221Collection" ,"transferLifeEventLasc3221Collection")
		Config.namingMap.put("ライフイベント_Lasc3321_02Collection" ,"transferLifeEventLasc3321_02Collection")
		Config.namingMap.put("ライフイベント_Lasc3321Collection" ,"transferLifeEventLasc3321Collection")
		Config.namingMap.put("ライフイベント_Lasc3420Collection" ,"transferLifeEventLasc3420Collection")
		Config.namingMap.put("ライフイベント_Lasc3441Collection" ,"transferLifeEventLasc3441Collection")
		Config.namingMap.put("ライフイベント_Lasc3451Collection" ,"transferLifeEventLasc3451Collection")
		Config.namingMap.put("ライフイベント_Lasc3452Collection" ,"transferLifeEventLasc3452Collection")
		Config.namingMap.put("ライフイベント_Lasc3453Collection" ,"transferLifeEventLasc3453Collection")
		Config.namingMap.put("ライフイベント_Lasc3461Collection" ,"transferLifeEventLasc3461Collection")
		Config.namingMap.put("ライフイベント_Lasc3463Collection" ,"transferLifeEventLasc3463Collection")
		Config.namingMap.put("ライフイベント_Lasc3470Collection" ,"transferLifeEventLasc3470Collection")
		Config.namingMap.put("ライフイベント_Lasc3521Collection" ,"transferLifeEventLasc3521Collection")
		Config.namingMap.put("ライフイベント_Lasc3621Collection" ,"transferLifeEventLasc3621Collection")
		Config.namingMap.put("ライフイベント_Lasc3631Collection" ,"transferLifeEventLasc3631Collection")
		Config.namingMap.put("ライフイベント_Lasc3721Collection" ,"transferLifeEventLasc3721Collection")
		Config.namingMap.put("ライフイベント_Lasc3731Collection" ,"transferLifeEventLasc3731Collection")
		Config.namingMap.put("ライフイベント_Lasc3740Collection" ,"transferLifeEventLasc3740Collection")
		Config.namingMap.put("ライフイベント_Lasc3821Collection" ,"transferLifeEventLasc3821Collection")
		Config.namingMap.put("ライフイベント_Lasc5220Collection" ,"transferLifeEventLasc5220Collection")
		Config.namingMap.put("ライフイベント_Lasc5241Collection" ,"transferLifeEventLasc5241Collection")
		Config.namingMap.put("ライフイベント_Lasc5251Collection" ,"transferLifeEventLasc5251Collection")
		Config.namingMap.put("ライフイベント_Lasc5261Collection" ,"transferLifeEventLasc5261Collection")
		Config.namingMap.put("ライフイベント_Lasc5320Collection" ,"transferLifeEventLasc5320Collection")
		Config.namingMap.put("ライフイベント_Lasc5330Collection" ,"transferLifeEventLasc5330Collection")
		Config.namingMap.put("ライフイベント_Lasc5420_01Collection" ,"transferLifeEventLasc5420_01Collection")
		Config.namingMap.put("ライフイベント_Lasc5420Collection" ,"transferLifeEventLasc5420Collection")
		Config.namingMap.put("ライフイベント_Lasc5430_01Collection" ,"transferLifeEventLasc5430_01Collection")
		Config.namingMap.put("ライフイベント_Lasc5430Collection" ,"transferLifeEventLasc5430Collection")
		Config.namingMap.put("ライフイベント_Lasc5450Collection" ,"transferLifeEventLasc5450Collection")
		Config.namingMap.put("ライフイベント_Lasc5461Collection" ,"transferLifeEventLasc5461Collection")
		Config.namingMap.put("ライフイベント_Lasc5462Collection" ,"transferLifeEventLasc5462Collection")
		Config.namingMap.put("ライフイベント_Lasc5463_01Collection" ,"transferLifeEventLasc5463_01Collection")
		Config.namingMap.put("ライフイベント_Lasc5463_02Collection" ,"transferLifeEventLasc5463_02Collection")
		Config.namingMap.put("ライフイベント_Lasc5464Collection" ,"transferLifeEventLasc5464Collection")
		Config.namingMap.put("ライフイベント_Lasc5470Collection" ,"transferLifeEventLasc5470Collection")
		Config.namingMap.put("ライフイベント_Lasc5481Collection" ,"transferLifeEventLasc5481Collection")
		Config.namingMap.put("ライフイベント_Lasc6420Collection" ,"transferLifeEventLasc6420Collection")
		Config.namingMap.put("ライフイベント_Lasc6431Collection" ,"transferLifeEventLasc6431Collection")
		Config.namingMap.put("ライフイベント_Lasc6432Collection" ,"transferLifeEventLasc6432Collection")
		Config.namingMap.put("ライフイベント_Lasc6500Collection" ,"transferLifeEventLasc6500Collection")
		Config.namingMap.put("ライフイベント_Lasc6600Collection" ,"transferLifeEventLasc6600Collection")
		Config.namingMap.put("ライフイベント_Lasc7221Collection" ,"transferLifeEventLasc7221Collection")
		Config.namingMap.put("ライフイベント_Lasc7231_01Collection" ,"transferLifeEventLasc7231_01Collection")
		Config.namingMap.put("ライフイベント_Lasc7231_02Collection" ,"transferLifeEventLasc7231_02Collection")
		Config.namingMap.put("ライフイベント_Lasc7232_01Collection" ,"transferLifeEventLasc7232_01Collection")
		Config.namingMap.put("ライフイベント_Lasc7232_02Collection" ,"transferLifeEventLasc7232_02Collection")
		Config.namingMap.put("ライフイベント_Lasc7233_01Collection" ,"transferLifeEventLasc7233_01Collection")
		Config.namingMap.put("ライフイベント_Lasc7234_01Collection" ,"transferLifeEventLasc7234_01Collection")
		Config.namingMap.put("ライフイベント_Lasc7234_02Collection" ,"transferLifeEventLasc7234_02Collection")
		
		
		
		Config.namingMap.put("かなえる_Lasc6420Collection"  , "transferKanaeruLasc6420Collection")
		Config.namingMap.put("かなえる_Lasc6431Collection"  , "transferKanaeruLasc6431Collection")
		Config.namingMap.put("かなえる_Lasc6432Collection"  , "transferKanaeruLasc6432Collection")
		Config.namingMap.put("かなえる_Lasc6500Collection"  , "transferKanaeruLasc6500Collection")
		Config.namingMap.put("かなえる_Lasc6600Collection"  , "transferKanaeruLasc6600Collection")
		Config.namingMap.put("その他_Lasc7500Collection"  , "transferSonotaLasc7500Collection")
		Config.namingMap.put("その他_Lasc8100Collection"  , "transferSonotaLasc8100Collection")
		Config.namingMap.put("支える_Lasc7221Collection"  , "transferSasaeruLasc7221Collection")
		Config.namingMap.put("支える_Lasc7231_01Collection"  , "transferSasaeruLasc7231_01Collection")
		Config.namingMap.put("支える_Lasc7231_02Collection"  , "transferSasaeruLasc7231_02Collection")
		Config.namingMap.put("支える_Lasc7232_01Collection"  , "transferSasaeruLasc7232_01Collection")
		Config.namingMap.put("支える_Lasc7232_02Collection"  , "transferSasaeruLasc7232_02Collection")
		Config.namingMap.put("支える_Lasc7233_01Collection"  , "transferSasaeruLasc7233_01Collection")
		Config.namingMap.put("支える_Lasc7234_01Collection"  , "transferSasaeruLasc7234_01Collection")
		Config.namingMap.put("支える_Lasc7234_02Collection"  , "transferSasaeruLasc7234_02Collection")
		Config.namingMap.put("支える_Lasc7235_01Collection"  , "transferSasaeruLasc7235_01Collection")
		Config.namingMap.put("支える_Lasc7235_02Collection"  , "transferSasaeruLasc7235_02Collection")
		Config.namingMap.put("支える_Lasc7236_01Collection"  , "transferSasaeruLasc7236_01Collection")
		Config.namingMap.put("支える_Lasc7236_02Collection"  , "transferSasaeruLasc7236_02Collection")
		Config.namingMap.put("支える_Lasc7237_01Collection"  , "transferSasaeruLasc7237_01Collection")
		Config.namingMap.put("支える_Lasc7237_02Collection"  , "transferSasaeruLasc7237_02Collection")
		Config.namingMap.put("支える_Lasc7238_01Collection"  , "transferSasaeruLasc7238_01Collection")
		Config.namingMap.put("支える_Lasc7238_02Collection"  , "transferSasaeruLasc7238_02Collection")
		Config.namingMap.put("支える_Lasc7239_01Collection"  , "transferSasaeruLasc7239_01Collection")
		Config.namingMap.put("支える_Lasc7239_02Collection"  , "transferSasaeruLasc7239_02Collection")
		Config.namingMap.put("支える_Lasc7240_01Collection"  , "transferSasaeruLasc7240_01Collection")
		Config.namingMap.put("支える_Lasc7240_02Collection"  , "transferSasaeruLasc7240_02Collection")
		Config.namingMap.put("支える_Lasc7242Collection"  , "transferSasaeruLasc7242Collection")
		Config.namingMap.put("支える_Lasc7243_01Collection"  , "transferSasaeruLasc7243_01Collection")
		Config.namingMap.put("支える_Lasc7243_02Collection"  , "transferSasaeruLasc7243_02Collection")
		Config.namingMap.put("支える_Lasc7321Collection"  , "transferSasaeruLasc7321Collection")
		Config.namingMap.put("準備済資金_Lasc5220Collection"  , "transferJunbizumishikinLasc5220Collection")
		Config.namingMap.put("準備済資金_Lasc5241Collection"  , "transferJunbizumishikinLasc5241Collection")
		Config.namingMap.put("準備済資金_Lasc5251Collection"  , "transferJunbizumishikinLasc5251Collection")
		Config.namingMap.put("準備済資金_Lasc5261Collection"  , "transferJunbizumishikinLasc5261Collection")
		Config.namingMap.put("準備済資金_Lasc5320Collection"  , "transferJunbizumishikinLasc5320Collection")
		Config.namingMap.put("準備済資金_Lasc5330Collection"  , "transferJunbizumishikinLasc5330Collection")
		Config.namingMap.put("準備済資金_Lasc5420_01Collection"  , "transferJunbizumishikinLasc5420_01Collection")
		Config.namingMap.put("準備済資金_Lasc5420Collection"  , "transferJunbizumishikinLasc5420Collection")
		Config.namingMap.put("準備済資金_Lasc5430_01Collection"  , "transferJunbizumishikinLasc5430_01Collection")
		Config.namingMap.put("準備済資金_Lasc5430Collection"  , "transferJunbizumishikinLasc5430Collection")
		Config.namingMap.put("準備済資金_Lasc5450Collection"  , "transferJunbizumishikinLasc5450Collection")
		Config.namingMap.put("準備済資金_Lasc5461Collection"  , "transferJunbizumishikinLasc5461Collection")
		Config.namingMap.put("準備済資金_Lasc5462Collection"  , "transferJunbizumishikinLasc5462Collection")
		Config.namingMap.put("準備済資金_Lasc5463_01Collection"  , "transferJunbizumishikinLasc5463_01Collection")
		Config.namingMap.put("準備済資金_Lasc5463_02Collection"  , "transferJunbizumishikinLasc5463_02Collection")
		Config.namingMap.put("準備済資金_Lasc5464Collection"  , "transferJunbizumishikinLasc5464Collection")
		Config.namingMap.put("準備済資金_Lasc5470Collection"  , "transferJunbizumishikinLasc5470Collection")
		Config.namingMap.put("準備済資金_Lasc5481Collection"  , "transferJunbizumishikinLasc5481Collection")
		
		
		
		Config.namingMap.put("LRMS既加入保険分析_Lssc0601_01Collection"  , "transferKikanyuLssc0601_01Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0601Collection"  , "transferKikanyuLssc0601Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0602_01Collection"  , "transferKikanyuLssc0602_01Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0602Collection"  , "transferKikanyuLssc0602Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0603_01Collection"  , "transferKikanyuLssc0603_01Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0603Collection"  , "transferKikanyuLssc0603Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0604Collection"  , "transferKikanyuLssc0604Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0605Collection"  , "transferKikanyuLssc0605Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0606Collection"  , "transferKikanyuLssc0606Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0607Collection"  , "transferKikanyuLssc0607Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0608Collection"  , "transferKikanyuLssc0608Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0609Collection"  , "transferKikanyuLssc0609Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0610Collection"  , "transferKikanyuLssc0610Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0611Collection"  , "transferKikanyuLssc0611Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0612Collection"  , "transferKikanyuLssc0612Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0613Collection"  , "transferKikanyuLssc0613Collection")
		Config.namingMap.put("LRMS既加入保険分析_Lssc0614Collection"  , "transferKikanyuLssc0614Collection")
		
		
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_P_W"  , "transferKikanyuTLrmsOldPW")
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_PLCY_INFO"  , "transferKikanyuTLrmsOldPlcyInfo")
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_RIDR_INFO"  , "transferKikanyuTLrmsOldRidrInfo")
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_S_MANKI_MEISAI"  , "transferKikanyuTLrmsOldSMankiMeisai")
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_SUB_ACNT"  , "transferKikanyuTLrmsOldSubAcnt")
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_SUB_CARE"  , "transferKikanyuTLrmsOldSubCare")
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_SUB_CHILD"  , "transferKikanyuTLrmsOldSubChild")
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_SUB_KJNKN"  , "transferKikanyuTLrmsOldSubKjnkn")
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_SUB_NASHI"  , "transferKikanyuTLrmsOldSubNashi")
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_SUB_SHUNYUHOSHO"  , "transferKikanyuTLrmsOldSubShunyuhosho")
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_SUB_TEIGEN"  , "transferKikanyuTLrmsOldSubTeigen")
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_SUB_TEIKI"  , "transferKikanyuTLrmsOldSubTeiki")
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_SUB_TEIKI_IRYO"  , "transferKikanyuTLrmsOldSubTeikiIryo")
		Config.namingMap.put("ＬＲＭＳ既加入保険分析_L_T_LRMS_OLD_SUB_TEIZO"  , "transferKikanyuTLrmsOldSubTeizo")
		
		
		Config.namingMap.put("かなえる_L_T_LNAS_KNERSKN"  , "transferTLnasKnerskn")
		Config.namingMap.put("かなえる_L_T_LNAS_KNERSKN_PP"  , "transferTLnasKnersknPp")
		Config.namingMap.put("かなえる_L_T_LNAS_KNERTSK_SHUNYU_UP"  , "transferTLnasKnertskShunyuUp")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVJTK_JLOAN"  , "transferTLnasLevjtkJloan")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVJTK_JLOAN_KKAE"  , "transferTLnasLevjtkJloanKkae")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVJTK_JLOAN_SYKN"  , "transferTLnasLevjtkJloanSykn")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVJTK_SHIKIN"  , "transferTLnasLevjtkShikin")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVKKN_SHIKIN"  , "transferTLnasLevkknShikin")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVKYI_SHIKIN"  , "transferTLnasLevkyiShikin")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVRYK_SHIKIN"  , "transferTLnasLevrykShikin")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVSCL_CRRDSIN"  , "transferTLnasLevsclCrrdsin")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVSCL_JTGN"  , "transferTLnasLevsclJtgn")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVSCL_SEIKATSUHI"  , "transferTLnasLevsclSeikatsuhi")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVSCL_SHIKIN"  , "transferTLnasLevsclShikin")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVSNT_SHIKIN"  , "transferTLnasLevsntShikin")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVTIK_LOAN"  , "transferTLnasLevtikLoan")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVTIK_SHIKIN"  , "transferTLnasLevtikShikin")
		Config.namingMap.put("共通部_L_T_LNAS_HNOTE"  , "transferTLnasHnote")
		Config.namingMap.put("共通部_L_T_LNAS_NEJ_DATA"  , "transferTLnasNejData")
		Config.namingMap.put("共通部_L_T_LNAS_PFAMLY"  , "transferTLnasPfamly")
		Config.namingMap.put("共通部_L_T_LNAS_PLAN_KIHON"  , "transferTLnasPlanKihon")
		Config.namingMap.put("共通部_L_T_LNAS_SHOKAI_IRAI"  , "transferTLnasShokaiIrai")
		Config.namingMap.put("共通部_L_T_LNAS_WDKK_COMMENT"  , "transferTLnasWdkkComment")
		Config.namingMap.put("支える_L_T_LNAS_SSKPLN_SNSN_DET"  , "transferTLnasSskplnSnsnDet")
		Config.namingMap.put("準備済資金_L_T_LNAS_JBCORP"  , "transferTLnasJbcorp")
		Config.namingMap.put("準備済資金_L_T_LNAS_JBKOJI"  , "transferTLnasJbkoji")
		Config.namingMap.put("準備済資金_L_T_LNAS_JBKOJI_GCHKN_DET"  , "transferTLnasJbkojiGchknDet")
		Config.namingMap.put("準備済資金_L_T_LNAS_JBKOJI_SCHKN_DET"  , "transferTLnasJbkojiSchknDet")
		Config.namingMap.put("準備済資金_L_T_LNAS_JBKOJI_SECLIFJOB"  , "transferTLnasJbkojiSeclifjob")
		Config.namingMap.put("準備済資金_L_T_LNAS_JBKOJI_SEIHO_NENKIN"  , "transferTLnasJbkojiSeihoNenkin")
		Config.namingMap.put("準備済資金_L_T_LNAS_JBKUNI"  , "transferTLnasJbkuni")
		Config.namingMap.put("準備済資金_L_T_LNAS_JBKUNI_CP"  , "transferTLnasJbkuniCp")
		Config.namingMap.put("準備済資金_L_T_LNAS_JBKUNI_CP_DET"  , "transferTLnasJbkuniCpDet")
		
		
		
		Config.namingMap.put("かなえる_L_T_LNAS_KNERSKN_SEIKATSUHI1"  , "transferTLnasKnersknSeikatsuhi_Genzai")
		Config.namingMap.put("かなえる_L_T_LNAS_KNERSKN_SEIKATSUHI2"  , "transferTLnasKnersknSeikatsuhi_Syorai")
		

		
		
		Config.namingMap.put("支える_L_T_LNAS_SASAERU_SIEPLN1"  , "transferTLnasSasaeruSiepln_Kyouik")
		Config.namingMap.put("支える_L_T_LNAS_SASAERU_SIEPLN2"  , "transferTLnasSasaeruSiepln_Kekon")
		Config.namingMap.put("支える_L_T_LNAS_SASAERU_SIEPLN3"  , "transferTLnasSasaeruSiepln_Ryokou")
		Config.namingMap.put("支える_L_T_LNAS_SASAERU_SIEPLN4"  , "transferTLnasSasaeruSiepln_Sonotakeikaku")
		Config.namingMap.put("支える_L_T_LNAS_SASAERU_SIEPLN5"  , "transferTLnasSasaeruSiepln_Izokuseikatsu")
		Config.namingMap.put("支える_L_T_LNAS_SASAERU_SIEPLN6"  , "transferTLnasSasaeruSiepln_Housework")
		Config.namingMap.put("支える_L_T_LNAS_SASAERU_SIEPLN7"  , "transferTLnasSasaeruSiepln_Shiboseiri")
		Config.namingMap.put("支える_L_T_LNAS_SASAERU_SIEPLN8"  , "transferTLnasSasaeruSiepln_Haigusyasyuunyu")
		Config.namingMap.put("支える_L_T_LNAS_SASAERU_SIEPLN9"  , "transferTLnasSasaeruSiepln_Sonotasyuunyu")
		
		Config.namingMap.put("支える_L_T_LNAS_SASAERU_SHIKIN1"  , "transferTLnasSasaeruShikin_Honnin")
		Config.namingMap.put("支える_L_T_LNAS_SASAERU_SHIKIN2"  , "transferTLnasSasaeruShikin_Haigusya")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVJTK_JLOAN1"  , "transferTLnasLevjtkJloan_Genzai")
		Config.namingMap.put("ライフイベント_L_T_LNAS_LEVJTK_JLOAN2"  , "transferTLnasLevjtkJloan_Syorai")
		
		Config.namingMap.put("準備済資金_L_T_LNAS_JBKOJI_HSSN_DET1"  , "transferTLnasJbkojiHssnDet_Zaisan")
		Config.namingMap.put("準備済資金_L_T_LNAS_JBKOJI_HSSN_DET2"  , "transferTLnasJbkojiHssnDet_Fusai")
		Config.namingMap.put("準備済資金_L_T_LNAS_JBKUNI_IZOKU1"  , "transferTLnasJbkuniIzoku_Honnin")
		Config.namingMap.put("準備済資金_L_T_LNAS_JBKUNI_IZOKU2"  , "transferTLnasJbkuniIzoku_Haigusya")
		
	}
}